### ISSUE TITLE
UX: Inventory GUI Improvements

### ISSUE THREAD

**Issue by knyghtmare** [babaissarkar/WISh#12]
### What I meant is this:
![image](https://github.com/user-attachments/assets/708db9c9-8218-42fa-bd92-a0223e91f5ce)

### Improvements to Make:

![image](https://github.com/user-attachments/assets/ebcfdcca-cf3f-4a04-9710-fe58abe47385)

- The 4 "Show" buttons should be renamed to "View Item" Or, maybe "View Weapon", "View Armor", "View Trinket" and "View Amulet"

![image](https://github.com/user-attachments/assets/a3dfa5b7-dba2-4d21-9321-2785bdddbf03)

- This "Show" button should be renamed to "View Storage Item". Also, maybe some way to note that player should one-click select an item in the storage list before clicking this button?

**Comment by babaissarkar** [comment]
Renaming the button names is easy, just modify the strings in inventory.cfg
file to your liking.
