### ISSUE TITLE
BUG: Clicking "Show" Button when storage is empty, gives Lua Error

### ISSUE THREAD

**Issue by knyghtmare** [babaissarkar/WISh#13]
![image](https://github.com/user-attachments/assets/a7da3677-0a1c-4bff-acf0-cc3770cc9ed0)

The Error message is:
![image](https://github.com/user-attachments/assets/980cdf36-f758-4117-a17d-da5417f1613a)

**Comment by babaissarkar** [comment]
@knyghtmare Please check this one as well.

Added checks to the View Inventory Item button. Also, the button will be enabled only when there's actually an item in storage and you select that item.

![Screenshot from 2024-10-02 17-54-04](https://github.com/user-attachments/assets/39cda2f4-b8e7-4f6d-a123-3a3e59ef352b) ![Screenshot from 2024-10-02 17-54-11](https://github.com/user-attachments/assets/819fabdc-78e4-4566-b5ce-74d1297c2e40)

**Comment by knyghtmare** [comment]
This can be closed
