### ISSUE TITLE
Feature: allow addition of some attribute that disallows some special items from being unequipped

### ISSUE THREAD

**Issue by knyghtmare** [babaissarkar/WISh#17]
- For example, if we have an item that is cursed...so, when equipped it grants both a buff and a debuff but since it's cursed, we dont want it to be removed and assigned to another unit or kept in storage.
- Other examples are story specific artifacts as `objects` so these have to be present with the designated character.

**Comment by babaissarkar** [comment]
Commit https://github.com/babaissarkar/WISh/commit/56c653de86dd4287dd39791cf371403f4f539c30 :

### Usage:
add `cursed=yes` inside the `[object]`, i.e.,
```ini
[object]
          id=arzenth
          name= _ "Arzenth"
          take_only_once=no
          image=items/staff-2.png
          description= _ "The Staff of Lightning, Arzenth."
          cursed = true
      
          [effect]
```

### UI
Clicking Unequip/Drop shows this:
![Screenshot from 2024-08-26 18-12-56](https://github.com/user-attachments/assets/8abab3dd-48b0-4537-b4ff-8b5ba4d60512)

**Comment by babaissarkar** [comment]
I'm also thinking about specifying the item type inside the `[object]` since ATM the macro remembers the object's type and not the object itself. This doesn't seem logical. In this way even if you move the object or store it somewhere else, the data still remains. Plus it helps with #10.

**Comment by knyghtmare** [comment]
I dont think `cursed=true/false` would be the right term to use. 
I would think it's like more like `lock_slot=yes` and then make the message modifiable. Or, something generic like "This artifact cannot be unequipped normally" Or actually allow editing the text.

**Comment by babaissarkar** [comment]
> I dont think `cursed=true/false` would be the right term to use. I would think it's like more like `lock_slot=yes` and then make the message modifiable. Or, something generic like "This artifact cannot be unequipped normally" Or actually allow editing the text.

Renamed to `locked` and you can customize the message text using `lock_msg` key. Message title is fixed.

Default message:
![Screenshot from 2024-08-26 18-43-35](https://github.com/user-attachments/assets/03374653-c8da-4bf0-a0e0-78f87d21517e)

**Comment by knyghtmare** [comment]
Nice.

**Comment by knyghtmare** [comment]
@babaissarkar What about when it's required to unequip the item for story-plot reasons? Will the scenarioWML way of removing objects/items not work if `locked=yes`?

**Comment by babaissarkar** [comment]
> @babaissarkar What about when it's required to unequip the item for story-plot reasons? Will the scenarioWML way of removing objects/items not work if `locked=yes`?

Normal ways of removing objects will still work. My changes only affect WISh UI buttons `Unequip` and `Drop`.
Although remove_modification will still work, I'd suggest using the `get_item_from_unit` function with `remove=yes` in `items.lua`. It takes care of some cleanup which otherwise might need to be done manually.

https://github.com/babaissarkar/WISh/blob/9d5c9ff167705e56e19b6a99ee6c046acb31747a/lua/items.lua#L74-L83
