### ISSUE TITLE
Feature: Drop Item on Floor on item-wielder death

### ISSUE THREAD

**Issue by knyghtmare** [babaissarkar/WISh#18]
- Gives player a chance to pick the item up again and ensure it is not lost forever

**Comment by babaissarkar** [comment]
Sorry, wrong push :(

**Comment by knyghtmare** [comment]
@babaissarkar Has there been any update on this? 

Maybe we can add some built-in event: if this item wielder dies, drop item on that hex?

**Comment by babaissarkar** [comment]
Found some relevant code here: https://wiki.wesnoth.org/DroppableItem
So just adding a [event] inside the put event should do the trick.

**Comment by babaissarkar** [comment]
Added some preliminary code which works for weapons. Will need more work:
- [x] make it work for all item types
- [x] do only if item exists. atm the item existance checking code needs more work.

**Comment by babaissarkar** [comment]
Works for all item types now.
