### ISSUE TITLE
UX: add text wrap to item description

### ISSUE THREAD

**Issue by knyghtmare** [babaissarkar/WISh#19]
Too long...
![image](https://github.com/user-attachments/assets/90e8b880-6601-4e5a-b9cc-43a6d409f6dc)

**Comment by babaissarkar** [comment]
Is this acceptable?

![Screenshot from 2024-08-27 16-48-54](https://github.com/user-attachments/assets/df16b3e1-8baa-464f-828e-3b6848145e77)

This has the small problem that the min height of the window is 200 always, and it shows scrollbars after that.

![Screenshot from 2024-08-27 16-51-49](https://github.com/user-attachments/assets/b9d9976f-ab47-4c6a-830f-8e38cbeba0cd)

(hit a couple gui2 limitations along the way.)

Edit: reduced min height to 100.

**Comment by knyghtmare** [comment]
This seems okay. Like what I needed for the lore rich item descriptions
