### ISSUE TITLE
BUG: if equipped item is unequipped, the trait is not removed

### ISSUE THREAD

**Issue by knyghtmare** [babaissarkar/WISh#22]
- Screenshots
![image](https://github.com/user-attachments/assets/fb88d58c-808e-46c6-b902-779a8e7f015b)
![image](https://github.com/user-attachments/assets/f478ce88-ca65-420a-be8c-04b2c717aa74)

**Comment by babaissarkar** [comment]
@knyghtmare does the fix work?

**Comment by knyghtmare** [comment]
Seems resolved.
