### ISSUE TITLE
Feature: Show Unit name and Type Name in Inventory Dialog

### ISSUE THREAD

**Issue by knyghtmare** [babaissarkar/WISh#23]
- When we right-click and select "Inventory" on a unit, we see the inventory of that unit
- However, it would be nice to see which unit we are showing the inventory for. This can at minimum, the unit's name and the unit's type.
- Like "Kerlan: The Drake Warden", not as the heading but maybe one text after it.

**Comment by babaissarkar** [comment]
@knyghtmare Does this work?
![Screenshot from 2024-09-30 15-25-09](https://github.com/user-attachments/assets/b37eee6c-2adc-4aab-8bd1-589d2c411c37)

**Comment by knyghtmare** [comment]
@babaissarkar This works amazingly
