### ISSUE TITLE
Refine `WISH_ITEM_PICKUP` to include TYPE, CANNOT_TAKE_TEXT, DESCRIPTION, TAKE_IT_STRING LEAVE_IT_STRING

### ISSUE THREAD

**Issue by knyghtmare** [babaissarkar/WISh#4]
- I tried making one but it seems hard-fixed on the weapon slot. 
- Then I see macro and it might need to be expanded to add additional arguments

**Comment by babaissarkar** [comment]
> * I tried making one but it seems hard-fixed on the weapon slot.

Type is not fixated, it's an optional argument. "weapon" is the default value.

```ini
            {WISH_ITEM_PICK_UP arzenth 12 13 (level=1) items/staff-2.png
                (
                    [object]
                        id=my_item
                        name= _ "Item"
                        take_only_once=no
                        image=items/staff-2.png
                        description= _ "Test Item"
        
                        # effects here
                    [/object]
                )
                TYPE="armor" # if you don't specify it defaults to "weapon"
            }
```

> Then I see macro and it might need to be expanded to add additional arguments

The rest are not implemented yet.

**Comment by babaissarkar** [comment]
@knyghtmare Does https://github.com/babaissarkar/WISh/commit/cc2a1ba9f054ba7b507dd78a1d71731360d368f2 fix it?

`TAKE_IT_STRING` and `LEAVE_IT_STRING` are also optional arguments now.
(Description is to be passed via the object's description key)

**Comment by knyghtmare** [comment]
It does work now. Thanks.
Would be nice if `TYPE` is also specifiable at the macro level.

**Comment by babaissarkar** [comment]
> Would be nice if `TYPE` is also specifiable at the macro level.

What do you mean by `macro level`? (snippet?)

**Comment by knyghtmare** [comment]
```ini
#define WISH_ITEM_PICK_UP _ITEM_ID _X _Y _CAN_TAKE_FILTER_WML _CANNOT_TAKE_TEXT _IMAGE _OBJECT_WML _ITEM_TYPE
#enddef
```

**Comment by babaissarkar** [comment]
> ```ini
> #define WISH_ITEM_PICK_UP _ITEM_ID _X _Y _CAN_TAKE_FILTER_WML _CANNOT_TAKE_TEXT _IMAGE _OBJECT_WML _ITEM_TYPE
> #enddef
> ```

You can do `TYPE={_TYPE}`

**Comment by knyghtmare** [comment]
Yeah, that can work. You can close this ticket now.
