### ISSUE TITLE
[FR] New icon to show on sidebar or New Trait to show unit has item equipped. 

### ISSUE THREAD

**Issue by knyghtmare** [babaissarkar/WISh#6]
![image](https://github.com/user-attachments/assets/8555e4da-84bc-49ec-a447-576c598df2b6)
- Item gives +2 HP, but here you cannot tell if he has the item equipped or not.
- Thus, maybe some built-in way in WISh to show unit has item equipped. Like sidebar can show item slots (maybe a bit too ambitous)
- Or, a non-combat trait called "equipped" or name of the item as trait (might be too many if all slots) that can be deequipped/equipped

**Comment by babaissarkar** [comment]
Added in https://github.com/babaissarkar/WISh/commit/c858526d850cf574bc40a11a83d7bd19844f04b6
I also plan to add an overlay in future.
![Screenshot from 2024-08-20 18-11-48](https://github.com/user-attachments/assets/f52a7813-049b-4d05-b415-ef64ed603bcc)

**Comment by babaissarkar** [comment]
due to the limitations of the gui1 sidebar, too many items might get it cut off.

**Comment by knyghtmare** [comment]
for one word ids, this works, but kind of looks bad with big ids like `rock_of_frost_resistance`. Is there any way to just show what type of equipment a unit has instead of the exact id?

**Comment by babaissarkar** [comment]
> for one word ids, this works, but kind of looks bad with big ids like `rock_of_frost_resistance`. Is there any way to just show what type of equipment a unit has instead of the exact id?

Is just showing the type enough, or name needed?

**Comment by knyghtmare** [comment]
The name would be the best thing to show here.

**Comment by babaissarkar** [comment]
Does this work? It shows the name now.

![Screenshot from 2024-08-21 09-35-58](https://github.com/user-attachments/assets/355cf812-9a24-40b1-b931-e7cd2ff5e3f0)

**Comment by knyghtmare** [comment]
> Does this work? It shows the name now.

Yeah, it does!

**Comment by babaissarkar** [comment]
relevance of Overlay/Status for equip should be discussed in another issue IMO.
